/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module circuit_v7(x1, x2, x3, x4, y1, y2, y3, y4);
  wire _00_;
  wire _01_;
  wire _02_;
  wire [3:0] _03_;
  input x1;
  wire x1;
  input x2;
  wire x2;
  input x3;
  wire x3;
  input x4;
  wire x4;
  output y1;
  wire y1;
  output y2;
  wire y2;
  output y3;
  wire y3;
  output y4;
  wire y4;
  LUT4 #(
    .INIT(16'ha334)
  ) _04_ (
    .I0(_03_[3]),
    .I1(_03_[2]),
    .I2(_03_[1]),
    .I3(_03_[0]),
    .O(_00_)
  );
  LUT4 #(
    .INIT(16'h4001)
  ) _05_ (
    .I0(_03_[0]),
    .I1(_03_[1]),
    .I2(_03_[2]),
    .I3(_03_[3]),
    .O(_01_)
  );
  LUT3 #(
    .INIT(8'h1c)
  ) _06_ (
    .I0(_03_[1]),
    .I1(_03_[3]),
    .I2(_03_[0]),
    .O(_02_)
  );
  IBUF _07_ (
    .I(x1),
    .O(_03_[2])
  );
  IBUF _08_ (
    .I(x2),
    .O(_03_[3])
  );
  IBUF _09_ (
    .I(x3),
    .O(_03_[0])
  );
  IBUF _10_ (
    .I(x4),
    .O(_03_[1])
  );
  OBUF _11_ (
    .I(_03_[3]),
    .O(y1)
  );
  OBUF _12_ (
    .I(_00_),
    .O(y2)
  );
  OBUF _13_ (
    .I(_01_),
    .O(y3)
  );
  OBUF _14_ (
    .I(_02_),
    .O(y4)
  );
endmodule
