/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module circuit_v7(x1, x2, x3, x4, y1, y2, y3, y4);
  wire \dd1.a ;
  wire \dd10.c ;
  wire \dd11.y ;
  wire \dd2.a ;
  wire \dd4.c ;
  wire \dd5.y ;
  wire \dd6.y ;
  input x1;
  wire x1;
  input x2;
  wire x2;
  input x3;
  wire x3;
  input x4;
  wire x4;
  output y1;
  wire y1;
  output y2;
  wire y2;
  output y3;
  wire y3;
  output y4;
  wire y4;
  LUT4 #(
    .INIT(16'h4001)
  ) _00_ (
    .I0(\dd2.a ),
    .I1(\dd1.a ),
    .I2(\dd10.c ),
    .I3(\dd4.c ),
    .O(\dd5.y )
  );
  LUT3 #(
    .INIT(8'h1c)
  ) _01_ (
    .I0(\dd10.c ),
    .I1(\dd1.a ),
    .I2(\dd2.a ),
    .O(\dd6.y )
  );
  LUT4 #(
    .INIT(16'ha334)
  ) _02_ (
    .I0(\dd1.a ),
    .I1(\dd4.c ),
    .I2(\dd2.a ),
    .I3(\dd10.c ),
    .O(\dd11.y )
  );
  IBUF _03_ (
    .I(x1),
    .O(\dd4.c )
  );
  IBUF _04_ (
    .I(x2),
    .O(\dd1.a )
  );
  IBUF _05_ (
    .I(x3),
    .O(\dd2.a )
  );
  IBUF _06_ (
    .I(x4),
    .O(\dd10.c )
  );
  OBUF _07_ (
    .I(\dd1.a ),
    .O(y1)
  );
  OBUF _08_ (
    .I(\dd11.y ),
    .O(y2)
  );
  OBUF _09_ (
    .I(\dd5.y ),
    .O(y3)
  );
  OBUF _10_ (
    .I(\dd6.y ),
    .O(y4)
  );
endmodule
